version: '3'
services:
  lupus-garupus-back:
    build: ./lupus-garupus-back
    environment:
      NODE_ENV: docker
      APP_LOG_LEVEL: debug
    ports:
      - "0.0.0.0:3030:3030"
    volumes:
      - ./lupus-garupus-back:/opt/lupus-garupus-back

  lupus-garupus-front:
    build: ./lupus-garupus-front
    environment:
      NODE_ENV: docker
      APP_LOG_LEVEL: debug
    ports:
      - "0.0.0.0:3001:3000"
    volumes:
      - ./lupus-garupus-front:/opt/lupus-garupus-front
